### PR TITLE
Bump numpy and scipy versions on py3 to handle libgfortran linking bug (was Temporarily disable MKL)

### PR DESCRIPTION
**Pull request by vighneshbirodkar**
Fix copied from
https://github.com/scikit-learn/scikit-learn/pull/6508

### CODE REVIEW

**Comment by vighneshbirodkar** [comment]
@mblondel I would appreciate it if you could review this. Travis on all other PRs is failing due to the issue

**Comment by mblondel** [comment]
+1 as a temporary fix

@ogrisel @fabianp Any idea what is causing the failure?

**Comment by fabianp** [comment]
I have no idea, we are not getting that error for [lightning's build](https://travis-ci.org/scikit-learn-contrib/lightning)

**Comment by vighneshbirodkar** [comment]
@mblondel The issue is specific to numpy version. Like lightning if we install latest numpy, scipy versions we don't encounter this problem.

**Comment by vighneshbirodkar** [comment]
I discussed with @amueller IRL and he suggested I merge this.

**Pull request merged**
